#!/bin/bash

echo "🎯 Claude Code Annotation Workflow Example"
echo "==========================================="
echo "Recommended one-liner:"
echo "  python scripts/run_workflow.py TASK_ID --repo \$(pwd)"
echo "    [--model-a claude-brocade-v22-p] [--model-b claude-opus-4-1-20250805]"
echo ""

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo "❌ Error: Not in a git repository"
    echo "Please run this from the root of your project repository"
    exit 1
fi

echo ""
echo "📋 Step 1: Initialize Model A Session"
echo "--------------------------------------"
echo "Command: python script1_model_a_init.py T123 [--model-id MODEL]"
echo ""
echo "This will:"
echo "  ✓ Create session directory (e.g., S1a2b3c4d/)"
echo "  ✓ Record base git commit"
echo "  ✓ Take 'before' code snapshot"
echo "  ✓ Set up metadata for Model A"
echo "  ✓ Initialize Claude Code session automatically"
echo "  ✓ Create task prompt template file"
echo ""
echo "After running Script 1:"
echo "  1. Claude Code should launch automatically"
echo "  2. Open task_prompt.txt in session folder"
echo "  3. Add your task prompt to the template"
echo "  4. Copy and paste into Claude Code"
echo "  5. Let Claude complete the task"
echo "  6. Do NOT commit changes"
echo ""

read -p "Press Enter to see Step 2..."

echo ""
echo "🔄 Step 2: Transition to Model B"
echo "--------------------------------"
echo "Command: python script2_model_b_init.py [--model-id MODEL]"
echo ""
echo "This will:"
echo "  ✓ Capture Model A results (after snapshot, diff)"
echo "  ✓ Copy Claude transcript (if found)"
echo "  ✓ Reset git to base commit"
echo "  ✓ Create new session for Model B"
echo "  ✓ Initialize Claude Code session for Model B"
echo "  ✓ Create fresh task prompt template"
echo ""
echo "After running Script 2:"
echo "  1. Claude Code should launch automatically (fresh session)"
echo "  2. Repository is reset to base commit (clean slate)"
echo "  3. Open task_prompt.txt in Model B session folder"
echo "  4. Use the SAME task prompt as Model A"
echo "  5. Copy and paste into Claude Code"
echo "  6. Let Claude complete the task"
echo "  7. Do NOT commit changes"
echo ""

read -p "Press Enter to see Step 3..."

echo ""
echo "✅ Step 3: Finalize Model B Session"
echo "-----------------------------------"
echo "Command: python script3_model_b_capture.py"
echo ""
echo "This will:"
echo "  ✓ Capture Model B results"
echo "  ✓ Copy Claude transcript"
echo "  ✓ Generate final summary"
echo "  ✓ Provide Airtable logging info"
echo ""

echo ""
echo "📤 Final Steps: Data Submission"
echo "-------------------------------"
echo "1. Upload session folders to Google Drive:"
echo "   - S1a2b3c4d/ (Model A results)"
echo "   - S5e6f7g8h/ (Model B results)"
echo ""
echo "2. Log in Airtable:"
echo "   - Task ID, prompt text"
echo "   - Session IDs, Drive links"
echo "   - Commit SHA, timestamps"
echo ""

echo ""
echo "🎉 Workflow Complete!"
echo "===================="
echo ""
echo "Generated Files:"
echo "  📁 Session directories with complete data"
echo "  📄 annotation_summary.json"
echo "  📊 Structured data ready for analysis"
echo ""
echo "For actual usage, run:"
echo "  python script1_model_a_init.py YOUR_TASK_ID"
echo ""
